[application]
#permit_debugging = false

[proxy]
socks_listen = 9050
# Port to use to listen for DNS requests.  0 means disabled.
dns_listen = 1053

[logging]
#console=info

# Supported variables are ARTI_CACHE, ARTI_CONFIG, ARTI_SHARED_DATA,
# ARTI_LOCAL_DATA, and USER_HOME.
#
# Multiple processes can share the same cache_dir.  If they do, one of them
# will download directory information for all of the others.
[storage]
#cache_dir = "${ARTI_CACHE}"
#state_dir = "${ARTI_LOCAL_DATA}"
